### ISSUE TITLE
Angular reporting this as a CommonJS dependency

### ISSUE THREAD

**Issue by kpeters-cbsi** [rhysd/validate-github-token#5]
This is more of a question than a bug. 

I'm using this package to validate GitHub auth tokens in an Angular 11 app. Every time I do `angular build`, I get this warning:

```
Warning: /work/ui/src/app/github-token-validator.service.ts depends on 'validate-github-token'. CommonJS or AMD dependencies can cause optimization bailouts.
For more info see: https://angular.io/guide/build#configuring-commonjs-dependencies
```

Any idea where this is coming from?

**Comment by rhysd** [comment]
Yes, this package is comomnjs module. I don't know Angular, but I guess Angular recommends to use ESM module since it is easy to be optimized by static analysis of imports graph. However, this package is very small and has only one dependency. I think this package doesn't affect your application's performance.

**Comment by kpeters-cbsi** [comment]
I think you're probably right; I was just curious. :)
